//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiscode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fiscode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - ABBIATEGRASSO	3002	32381
        /// - ACIREALE	3038	26202
        /// - AGRIGENTO	3038	16602
        /// - ALANO DI PIAVE	5035	60990
        /// - ALBA	6095	22500
        /// - ALBIATE	3104	32410
        /// - ALBIATE	3348	32410
        /// - ALESSANDRIA	6070	10499
        /// - ALESSANDRIA	6230	10400
        /// - ALESSANDRIA	10330	10400
        /// - ALTAMURA	6070	41330
        /// - ANCONA	3002	2604
        /// - ANCONA	6195	2601
        /// - ANCONA	10328	2601
        /// - AOSTA	5608	1201
        /// - AOSTA	10330	1200
        /// - APRILIA	5387	73922
        /// - APRILIA	5414	73922
        /// - ARCUGNANO	1025	88330
        /// - ARGENTA	3168	67171
        /// - AROSIO	1025	50890
        /// - ARZANO	3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bancheitaliane {
            get {
                return ResourceManager.GetString("bancheitaliane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A001	ABANO TERME
        ///A004	ABBADIA CERRETO
        ///A005	ABBADIA LARIANA
        ///A006	ABBADIA SAN SALVATORE
        ///A007	ABBASANTA
        ///A008	ABBATEGGIO
        ///A010	ABBIATEGRASSO
        ///A012	ABETONE
        ///M376	ABETONE CUTIGLIANO
        ///A013	ABRIOLA
        ///A014	ACATE
        ///A015	ACCADIA
        ///A016	ACCEGLIO
        ///A017	ACCETTURA
        ///A018	ACCIANO
        ///A019	ACCUMOLI
        ///A020	ACERENZA
        ///A023	ACERNO
        ///A024	ACERRA
        ///A025	ACI BONACCORSI
        ///A026	ACI CASTELLO
        ///A027	ACI CATENA
        ///A029	ACI SANT&apos;ANTONIO
        ///A028	ACIREALE
        ///A031	ACQUACANINA
        ///A032	ACQUAFONDATA
        ///A033	ACQUAFORMOSA
        ///A034	ACQUAFREDDA
        ///A035	ACQUALAGNA
        ///A03 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Codicicatastali {
            get {
                return ResourceManager.GetString("Codicicatastali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 084	Agrigento
        ///006	Alessandria
        ///042	Ancona
        ///007	Aosta
        ///051	Arezzo
        ///044	Ascoli Piceno
        ///005	Asti
        ///064	Avellino
        ///072	Bari
        ///025	Belluno
        ///062	Benevento
        ///016	Bergamo
        ///037	Bologna
        ///120	Bologna 2
        ///021	Bolzano
        ///017	Brescia
        ///098	Brescia 2
        ///074	Brindisi
        ///092	Cagliari
        ///085	Caltanissetta
        ///070	Campobasso
        ///061	Caserta
        ///087	Catania
        ///069	Chieti
        ///013	Como-Lecco
        ///078	Cosenza
        ///019	Cremona
        ///004	Cuneo
        ///079	CZ-KR-VV
        ///086	Enna
        ///038	Ferrara
        ///048	Firenze
        ///097	Firenze 2 (Prato)
        ///071	Foggia
        ///040	Forlì-Rimini
        ///060	Frosinone
        ///010	Genova [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Codiciiva {
            get {
                return ResourceManager.GetString("Codiciiva", resourceCulture);
            }
        }
    }
}
